# Generated by Django 4.1.4 on 2023-01-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu_tree", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="parent_id",
        ),
    ]
