# Generated by Django 4.1.4 on 2023-01-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu_tree", "0002_remove_menu_parent_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="parent_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu_tree.menu",
            ),
            preserve_default=False,
        ),
    ]
