# Generated by Django 4.1.4 on 2023-01-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_tree", "0003_menu_parent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="url",
            field=models.SlugField(max_length=200),
        ),
    ]
