# Generated by Django 4.1.4 on 2023-01-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu_tree", "0004_alter_menu_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="url",
            new_name="slug",
        ),
    ]
